version: '2'

services:

  wordpress:
    image: wordpress
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_USER: wp-admin
      WORDPRESS_DB_PASSWORD: 1SoNUpP6AYPDaAm1
      WORDPRESS_DB_HOST: db
    depends_on:
      - db
    links:
      - db:mysql

  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 32e+ytGTjzDJgK5v
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wp-admin
      MYSQL_PASSWORD: 1SoNUpP6AYPDaAm1
